version: '3'

volumes:
  postgres: {}

services:
  database:
    image: postgres:14-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
